config/routes.rb
Rails.application.routes.draw do
  root to: "news#search"

  devise_for :users

  resources :news, only: [ :index ] do
    collection do
      get "search"
      get "read_later", action: :read_later
    end
  end
  resources :read_laters, only: [ :create, :update, :destroy ]
  resources :tags, only: [:index, :create, :edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :read_laters
  has_many :users, through: :read_laters
  validates :title, presence: true
  validates :url, presence: true
  validates :source_name, presence: true
end

app/models/read_later.rb
class ReadLater < ApplicationRecord
  belongs_to :user
  belongs_to :article
  belongs_to :tag, optional: true
  validates :user, presence: true
  validates :article, presence: true
  validates :article_id, uniqueness: { scope: :user_id, message: "You have already saved this article." }
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :read_laters
  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tags
  has_many :read_laters, dependent: :destroy
  has_many :articles, through: :read_laters
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_user!

  def search
    query = params[:query].present? ? params[:query] : "latest"

    @articles = NewsApiService.fetch_all_articles(query)
    @articles = Kaminari.paginate_array(@articles).page(params[:page]).per(10)
  end

  def read_later
      @saved_articles = current_user.read_laters.includes(:article).page(params[:page]).per(10)
  end
end

app/controllers/read_laters_controller.rb
class ReadLatersController < ApplicationController
  before_action :authenticate_user!

  def create
    article = Article.find_by(url: params[:url])

    unless article
      article = Article.create(title: params[:title], url: params[:url], source_name: params[:name])
    end

    if current_user.read_laters.exists?(article_id: article.id)
      flash[:alert] = "You have already saved this article for later!"
    else
      current_user.read_laters.create(article: article)
      flash[:notice] = "Article saved for later!"
    end

    redirect_to search_news_index_path(query: params[:query])
  end

  def update
    @read_later = ReadLater.find(params[:id])
    if @read_later.update(read_later_params)
      redirect_to read_later_news_index_path, notice: "Tag updated successfully."
    else
      redirect_to read_later_news_index_path, alert: "Failed to update tag."
    end
  end

  def destroy
    @read_later = current_user.read_laters.find(params[:id])

    if @read_later.destroy
       flash[:notice] = "Article removed from list"
    else
      flash[:alert] = "Could not remove article"
    end

    redirect_to read_later_news_index_path
  end

  private

  def read_later_params
    params.require(:read_later).permit(:tag_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags = current_user.tags
    @tag = current_user.tags.build
  end

  def create
    @tag = current_user.tags.build(tag_params)

    if @tag.save
      flash[:notice] = "Tag created successfully"
      redirect_to tags_path
    else
      flash[:alert] = "Error creating tag"
      render :index
    end
  end

  def edit
    @tag = current_user.tags.find(params[:id])
  end

  def update
    @tag = current_user.tags.find(params[:id])

    if @tag.update(tag_params)
      flash[:notice] = "Tag updated successfully"
      redirect_to tags_path
    else
      flash[:alert] = "Error updating tag"
      render :edit
    end
  end

  def destroy
    @tag = current_user.tags.find(params[:id])
    @tag.read_laters.update_all(tag_id: nil)

    if @tag.destroy
      flash[:notice] = "Tag deleted"
    else
      flash[:alert] = "Error deleting tag"
    end
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/save_for_later_helper.rb
module SaveForLaterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "News Aggregator App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

     <!-- Carregando o SweetAlert2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.0/dist/sweetalert2.min.css">

    <!-- Carregando o SweetAlert2 JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.0/dist/sweetalert2.min.js"></script>

     <!-- Flowbite CSS -->
    <link href="https://cdn.jsdelivr.net/npm/flowbite@1.5.1/dist/flowbite.min.css" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-white p-4 shadow-lg border-b border-gray-200">
      <nav class="">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <div class="text-gray-800 font-semibold text-xl">
            <%= link_to "News Aggregator", root_path, class: "hover:text-gray-500 transition-colors" %>
          </div>

          <% if user_signed_in? %>

            <!-- Ícone de Hambúrguer para dispositivos móveis -->
            <button data-collapse-toggle="navbar-solid-bg" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-solid-bg" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
            </button>

            <!-- Menu de Navegação em Dispositivos Grandes -->
            <div class="hidden w-full md:block md:w-auto" id="navbar-solid-bg">
              <ul class="flex flex-col font-medium mt-4 rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent">
                <li>
                  <% if controller_name == "tags" && action_name == "index" %>
                    <%= link_to "← Back to Search", search_news_index_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% elsif controller_name == "news" && action_name == "search" %>
                    <%= link_to "Tags", tags_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% elsif controller_name == "read_laters" && action_name == "read_later" %>
                    <%= link_to "Tags", tags_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% end %>
                </li>

                <li>
                  <% if controller_name == "registrations" && action_name == "edit" %>
                    <%= link_to "← Back to Search", search_news_index_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% elsif controller_name == "news" && action_name == "search" %>
                    <%= link_to "Edit Profile", edit_user_registration_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% end %>
                </li>

                <li>

                  <% if controller_name == "news" && action_name == "search" %>
                    <%= link_to "Saved Articles", read_later_news_index_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% elsif controller_name == "news" && action_name == "read_later" %>     
                    <%= link_to "← Back to Search", search_news_index_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>   
                  <% end %>

                </li>

                <li>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                </li>
              </ul>
            </div>

            <!-- Menu de Navegação em Dispositivos Móveis -->
            <div id="mobile-menu" class="sm:hidden hidden flex-col absolute top-0 left-0 w-full bg-white shadow-lg border-t border-gray-200 z-10">
              <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent dark:bg-gray-800 md:dark:bg-transparent dark:border-gray-700">
                <li>
                  <% if controller_name == "tags" && action_name == "index" %>
                    <%= link_to "← Back to Search", search_news_index_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% elsif controller_name == "news" && action_name == "search" %>
                    <%= link_to "Tags", tags_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% elsif controller_name == "read_laters" && action_name == "read_later" %>
                    <%= link_to "Tags", tags_path, class: "block py-2 px-3 text-gray-800 dark:text-white hover:opacity-25 hover:text-gray-500 cursor-pointer" %>
                  <% end %>
                </li>

                <li>
                  <% if controller_name == "registrations" && action_name == "edit" %>
                    <%= link_to "← Back to Search", search_news_index_path, class: "block py-2 px-3 text-gray-800 dark:text-white" %>
                  <% elsif controller_name == "news" && action_name == "search" %>
                    <%= link_to "Edit Profile", edit_user_registration_path, class: "block py-2 px-3 text-gray-800 dark:text-white" %>
                  <% end %>
                </li>

                <li>
                  <% if controller_name == "news" && action_name == "search" %>
                    <%= link_to "Saved Articles", read_later_news_index_path, class: "block py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" %>
                  <% elsif controller_name == "news" && action_name == "read_later" %>     
                    <%= link_to "← Back to Search", search_news_index_path, class: "block py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" %>   
                  <% end %>
                </li>

                <li>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "block py-2 px-3 text-gray-900 hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" %>
                </li>
              </ul>
            </div>

          <% end %>
          
        </div>
      </nav>
    </header>
    
    <% if flash[:notice] %>
      <script>
        Swal.fire({
          toast: true,
          position: 'bottom-end',
          icon: 'success',
          title: "<%= flash[:notice] %>",
          showConfirmButton: false,
          timer: 3000,
        });
      </script>
    <% end %>
    <% if flash[:alert] %>
      <script>
        Swal.fire({
          toast: true,
          position: 'bottom-end',
          icon: 'error',
          title: "<%= flash[:alert] %>",
          showConfirmButton: false,
          timer: 3000,
        });
      </script>
    <% end %>
    
      <!-- Flowbite JS -->
    <script src="https://cdn.jsdelivr.net/npm/flowbite@1.5.1/dist/flowbite.min.js"></script>

    <!-- Alpine.js, necessário para interação do Flowbite -->
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.min.js" defer></script>

    <main class="container mx-auto mt-28 p-6 flex justify-center items-center">
      <%= yield %>
    </main>
    
  </body>
</html>

app/views/news/read_later.html.erb
<div class="flex flex-wrap justify-center items-start space-y-4 sm:space-y-0">
  <h1 class="text-3xl font-semibold text-gray-800 text-center my-2 w-full">Articles Saved for Later</h1>

  <% if @saved_articles.any? %>
    <ul class="space-y-6">
      <% @saved_articles.each do |read_later| %>
        <% if read_later.article.present? %>
          <li class="bg-white p-6 rounded-lg shadow-md hover:shadow-xl transition duration-300">
            <h2 class="text-2xl font-semibold text-gray-800"><%= read_later.article.title.present? ? read_later.article.title : "Untitled Article" %></h2>
            <p class="text-gray-600"><%= read_later.article.source_name.present? ? read_later.article.source_name : "Name not available" %></p>
            
            <div class="mt-4">
              <%= form_with(model: read_later, url: read_later_path(read_later), method: :patch, local: true) do |f| %>
                <div class="flex items-center space-x-2">
                  <%= f.label :tag_id, "Tag:", class: "text-gray-700 font-medium" %>
                  <%= f.collection_select :tag_id, Tag.where(user: current_user), :id, :name,
                        { prompt: "Select a tag" },
                        { class: "min-w-[12rem] border-gray-300 rounded-md shadow-sm p-2" } %>
                  <%= f.submit "Update", class: "bg-blue-500 hover:bg-blue-600 text-white px-3 py-1 rounded" %>
                </div>
              <% end %>
            </div>

            <% if read_later.tag.present? %>
              <div class="mt-2 text-sm text-gray-500">
                <span class="inline-block bg-blue-100 text-blue-800 px-2 py-1 rounded-full text-xs">
                  <%= read_later.tag.name %>
                </span>
              </div>
            <% end %>
            
            <a 
              href="<%= read_later.article.url %>" 
              target="_blank"
              class="mt-4 inline-block text-blue-600 hover:underline"
            >
              Read More
            </a>

            <%= 
              button_to "Remove",
              read_later_path(read_later.id),
              method: :delete, 
              data: { confirm: "Are you sure you want to remove this article from your list?" },
              class: "text-blue-600 hover:underline bg-transparent border-0 p-0 cursor-pointer font-semibold" 
            %>
          </li>
        <% else %>
          <p class="text-center text-gray-500"> Article no longer available.</p>
        <% end %>
      <% end %>
    </ul>

  <div class="mt-8 text-gray-500 mt-2 p-6">
    <%= paginate @saved_articles, class: "flex justify-center space-x-4" %>
  </div>

  <% else %>
    <p class="text-center text-gray-500">You have no saved articles.</p>
  <% end %>
</div>

app/views/news/search.html.erb
<div class="flex flex-wrap justify-center items-start space-y-4 sm:space-y-0">
  <form method="get" action="/news/search" class="w-full sm:flex sm:space-x-4 p-4 ">
    <h1 class="text-3xl font-semibold text-gray-800 text-center my-2 w-full">News Search</h1>
    <input 
      type="text" 
      name="query" 
      placeholder="Search for news..." 
      value="<%= params[:query] %>" 
      class="w-full sm:w-2/3 p-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
    />
    <button 
      type="submit"
      class="w-full sm:w-1/3 mt-4 sm:mt-0 p-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 hover:bg-gray-50 cursor-pointer"
    >
      Search
    </button>
  </form>

  <% if @articles.any? %>
    <ul class="space-y-6">
      <% @articles.each do |article| %>
        <li class="bg-white p-6 rounded-lg shadow-md hover:shadow-xl transition duration-300">
          <h2 class="text-2xl font-semibold text-gray-800"><%= article.title.present? ? article.title : "Untitled Article" %></h2>
          <p class="text-gray-600"><%= article.name.present? ? article.name : "Name not available"%></p>
          <p class="text-gray-500 mt-2"><%= article.description.present? ? article.description : "Description not available" %></p>
          <a 
            href="<%= article.url %>" 
            target="_blank"
            class="mt-4 inline-block text-blue-600 hover:underline"
          >
            Read More
          </a>
          <%= 
            button_to 'Save for Later', 
            read_laters_path(title: article.title, url: article.url, name: article.name), 
            method: :post,
            class: "mt-2 inline-block text-blue-600 hover:underline bg-transparent border-0 p-0 cursor-pointer font-semibold"
          %>
        </li>
      <% end %>
    </ul>
      
    <div class="mt-8 text-gray-500 mt-2 p-6">
      <%= paginate @articles, class: "flex justify-center space-x-4" %>
    </div>

  <% else %>
    <p class="text-center text-gray-500">No news found</p>
  <% end %>
</div>

app/views/tags/edit.html.erb
<div class="p-8 sm:p-6 md:p-8 rounded shadow-lg w-full max-w-md mx-auto">
  <h1 class="text-center text-3xl font-semibold text-gray-800 mb-6">Edit Tag</h1>

  <%= form_with model: @tag, local: true do |f| %>
    <div class="mb-4">
      <%= f.label :name, 'Tag Name', class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :name, value: @tag.name, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>

    <%= f.submit "Update Tag", class: "w-full py-2 px-4 bg-indigo-600 text-white font-semibold rounded-md shadow-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50" %>
  <% end %>

  <div class="mt-6">
    <%= link_to 'Back', tags_path, class: "text-blue-500 hover:text-blue-700 text-sm" %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="p-8 sm:p-6 md:p-8 rounded shadow-lg w-full max-w-md mx-auto">
  <h1 class="text-center text-3xl font-semibold text-gray-800 mb-6">Your Tags</h1>

  <%= form_with model: @tag, url: tags_path, local: true do |f| %>
    <div class="mb-4">
      <%= f.label :name, 'Tag Name', class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :name, placeholder: "Enter tag name", class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>

    <%= f.submit "Create Tag", class: "w-full py-2 px-4 bg-indigo-600 text-white font-semibold rounded-md shadow-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50" %>
  <% end %>

  <ul class="space-y-4">
    <% @tags.each do |tag| %>
      <% if tag.id.present? %>  
        <li class="flex items-center justify-between bg-white p-4 rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out">
          <span class="text-lg font-medium text-gray-800"><%= tag.name %></span>
          <div class="flex space-x-4">
            <%= link_to 'Edit', edit_tag_path(tag), class: "text-blue-600 hover:text-blue-800 transition duration-200" %>
            <%= link_to 'Delete', tag_path(tag), method: :delete, class: "text-red-600 hover:text-red-800 transition duration-200" %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>